print(len('python') == ('jargon'))
print('on' in 'python and jargon')
print('jargon' in 'I hope this course is not full of jargon')
print('on' in 'dragon and python')
print ('python')
len ('python') 