#day 2- 30days of python programming
FIRST_NAME = 'WILSON' 
LAST_NAME= "EMMANUEL" 
FULL_NAME= 'WILSONEMMANUEL'
COUNTRY= 'NIGERIA' 
CITY = 'AKURE' 
AGE = 12 
YEAR = 2021 
IS_MARRIED = 'NOTMARRIED' 
IS_TURE = 'TURE' 
IS_LIGHT = 'NOTLIGHT'
PERSON_INFO = (FIRST_NAME, LAST_NAME, FULL_NAME,COUNTRY, CITY, AGE, YEAR, IS_MARRIED, IS_TURE, IS_LIGHT )
type({'FIRST_NAME, LAST_NAME, FULL_NAME,COUNTRY, CITY, AGE, YEAR, IS_MARRIED, IS_TURE, IS_LIGHT'})
print(type)
help('keywords') 
